name: Get Secret from Azure Key Vault

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get secret from Key Vault
        id: getsecret
        uses: azure/secrets-store@v1
        with:
          keyvault: ${{ secrets.KEY_VAULT_NAME }}
          secrets: |
            ${{ secrets.SECRET_NAME }}

      - name: Print confirmation
        run: echo "✅ Secret fetched from Key Vault successfully!"
