name: get-secret
on:
  push:
    branches:
      - main

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get secrets from Key Vault
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "AZKeyGit"      # <-- Replace with your vault name
          secrets: "demo-secret"      # <-- Replace with your secret names

      - name: Show secret
        run: |
          echo "Secret 1 value: ${{ env.mySecret1 }}"
        
