name: Get Secret from Azure Key Vault

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get secret from Azure Key Vault
        id: getsecret
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KEY_VAULT_NAME }}
          secrets: |
            ${{ secrets.SECRET_NAME }}

      - name: Show result
        run: echo "✅ Secret fetched successfully!"

